### ISSUE TITLE
[prln_purchasing_report] Page margin laporan kurang kecil

### ISSUE THREAD

**Issue by andhit-r** [open-synergy/prln#25]
Page margin laporan kurang kecil.

**Comment by andhit-r** [comment]
Salah attach

[report_purchasing_pdf.pdf](https://github.com/open-synergy/prln/files/54843/report_purchasing_pdf.pdf)

**Comment by mikevhe18** [comment]
Mas, margin kurang kecil atau kurang lebar ?

**Comment by mikevhe18** [comment]
Mas, Issues ini udah selesai atau belum ?
