### ISSUE TITLE
[prln_purchasing_report] Tidak ada PPn tp kena x

### ISSUE THREAD

**Issue by andhit-r** [open-synergy/prln#81]

**Comment by mikevhe18** [comment]
Untuk Issues Ini, sudah dilakukan perbaikan. Perbaikan sudah di PR dan menunggu untuk di merged.
Kemudian sudah dibuatkan video tutorial untuk bagaimana caranya melakukan konfigurasi pajak. Videonya bisa dilihat di http://opensynergy-indonesia.usefedora.com/courses/odoo-6-1-prln-cara-konfigurasi-pajak-pada-report-purchasing/lectures/675973

**Comment by andhit-r** [comment]
Oke mantap
